- id: pgqueryguard-check
  name: pgqueryguard (check)
  description: Validate SQL in *.sql, *.psql, *.pgsql
  entry: pgqueryguard check .
  language: python
  pass_filenames: false
  types: [file]
  files: \.(sql|psql|pgsql)$

- id: pgqueryguard-report
  name: pgqueryguard (report)
  description: Generate HTML report via EXPLAIN
  entry: pgqueryguard report .
  language: python
  pass_filenames: false
  types: [file]
  files: \.(sql|psql|pgsql)$
