services:
  db:
    image: postgres:15
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d

volumes:
  db_data:
