services:
  backend:
    container_name: backend
    hostname: backend
    build:
      context: ..
      dockerfile: ./web/backend/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - ./backend/app:/app/app    
    command: >
      uvicorn app.main:app
      --host 0.0.0.0 --port 8080
      --reload --reload-dir /app/app
